### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by PengWenChen** [DaniMS-ZGZ/Panoramic-CNN-360-Saliency#2]
Hello,

I'm trying to reproduce the scores by using this code.
But the prediction was still far from the score on the paper.
Could you share the best model file that we can inference from it?

Many thanks.

**Comment by DaniMS-ZGZ** [comment]
Hi:

I've just updated the link to the model, just in case we uploaded the wrong one when we created this repository. 

You can find it [here](https://drive.google.com/file/d/1zvbrM9806tptYHWx5sc230NUCl98tybH/view?usp=sharing).

We have just checked it and it works with the command _python main.py --test 0_ (We include the image and predicted saliency map here too).

RGB Image:

![gt](https://user-images.githubusercontent.com/62649560/90024399-1c49a080-dcb5-11ea-8594-c68364e49c3e.png)

Predicted Saliency Map:

![predicted](https://user-images.githubusercontent.com/62649560/90024404-1d7acd80-dcb5-11ea-873b-d97bf7086624.png)

Regards.

**Comment by PengWenChen** [comment]
Hi there,

Thanks for your kindly sharing of the model.
I just tried this model on 7 images of salient!360 (2018), which are number 91, 93, 94, 95, 96, 97, 98.
And calculated the scores by the tool from salient!360 (2018). The average score of these 7 images are as follows.
![image](https://user-images.githubusercontent.com/37527080/90028828-ba0c9200-dcec-11ea-9916-e4801eb3407e.png)

It seems that there is still a gap between the scores on the paper.

**Comment by DaniMS-ZGZ** [comment]
Hi:

If you refer to the Salient360! dataset, it only contains 85 images, numbered from P2 to P89, so we do not know the images you are testing on.

Secondly, we did not use that salient!360 tool. We used a MATLAB-based code that you can find [here](https://github.com/cvzoya/saliency/tree/master/code_forMetrics). 

Regards,

**Comment by PengWenChen** [comment]
Hi,

Yes, the total number of images in Salient360! (2018) is 85. 
I mean 7 images with the name: 
‘P91_5376x2688.jpg’
‘P93_5376x2688.jpg’
‘P94_5376x2688.jpg’  
’P95_5376x2688.jpg‘
‘P96_5376x2688.jpg’
‘P97_5376x2688.jpg’
’P98_5376x2688.jpg‘

![image](https://user-images.githubusercontent.com/37527080/90046805-8852f580-dd03-11ea-90f7-95aa3e3186e8.png)

And predicted the saliency map with the model you shared.
Then I used the evaluation code from the salient360! benchmark in 2018.

Anyway, I'll try the matlab code. 
Thank you!

**Comment by PengWenChen** [comment]
By the way, I also downloaded salient!360 dataset in 2017, and the images were the same as 2018.
The total image number of images is 85 too, and it also exists P91, P93, P94, P95, P96, P97, P98. (They are in Eval folder).

![image](https://user-images.githubusercontent.com/37527080/90048209-c51fec00-dd05-11ea-81fd-1edf518cc23b.png)

I doubt if I have any misunderstanding here.

**Comment by DaniMS-ZGZ** [comment]
Hi:

Sorry about the misunderstood. We thought you were talking about the 91st image and so on, not the named "P91", etc.

We have tested our model with these images (we include here both the RGB and the predicted saliency maps):

![image_00_gt](https://user-images.githubusercontent.com/62649560/90048934-7a39b080-dcd4-11ea-8e08-07cb5f48cd29.jpg)
![image_00_sphere](https://user-images.githubusercontent.com/62649560/90048936-7ad24700-dcd4-11ea-8939-71069e36cb80.jpg)
![image_01_gt](https://user-images.githubusercontent.com/62649560/90048939-7ad24700-dcd4-11ea-9816-229c91282476.jpg)
![image_01_sphere](https://user-images.githubusercontent.com/62649560/90048940-7b6add80-dcd4-11ea-9986-0398cc0ce212.jpg)
![image_02_gt](https://user-images.githubusercontent.com/62649560/90048941-7b6add80-dcd4-11ea-9ace-4b246f8e5118.jpg)
![image_02_sphere](https://user-images.githubusercontent.com/62649560/90048942-7b6add80-dcd4-11ea-80f4-b8fc12b3ef3a.jpg)
![image_03_gt](https://user-images.githubusercontent.com/62649560/90048943-7c037400-dcd4-11ea-95f0-9de96ba57ae9.jpg)
![image_03_sphere](https://user-images.githubusercontent.com/62649560/90048945-7c037400-dcd4-11ea-932c-f629fda7fcee.jpg)
![image_04_gt](https://user-images.githubusercontent.com/62649560/90048947-7c9c0a80-dcd4-11ea-9bc3-59cc6be07d90.jpg)
![image_04_sphere](https://user-images.githubusercontent.com/62649560/90048948-7c9c0a80-dcd4-11ea-9372-cf0aa9033d12.jpg)
![image_05_gt](https://user-images.githubusercontent.com/62649560/90048950-7c9c0a80-dcd4-11ea-905a-086e849e631f.jpg)
![image_05_sphere](https://user-images.githubusercontent.com/62649560/90048954-7d34a100-dcd4-11ea-9ef1-441bd85b3b21.jpg)
![image_06_gt](https://user-images.githubusercontent.com/62649560/90048957-7d34a100-dcd4-11ea-8e6b-025aa220e25a.jpg)
![image_06_sphere](https://user-images.githubusercontent.com/62649560/90048959-7dcd3780-dcd4-11ea-87b9-aab8a8e76956.jpg)

As you can see, some scenes work better than the others (remember the small dataset the model was trained with), but it does such a decent work.

We have also computed the metrics for each of them, taking the corresponding GT for each one, and these are the results:

File: gt\SH91.jpg
Metric		Ours	
Similarity	0.6696
CC			0.7781
AUC_Borji	0.7287
AUC_Judd	0.7290
KLDiv		1.3519
NSS			3.4605
IG			3.3166

File: gt\SH93.jpg
Metric		Ours
Similarity	0.6955
CC			0.8337
AUC_Borji	0.8884
AUC_Judd	0.8888
KLDiv		0.6058
NSS			3.9970
IG			3.5050

File: gt\SH94.jpg
Metric		Ours	
Similarity	0.7948	
CC			0.8673	
AUC_Borji	0.6179
AUC_Judd	0.6178
KLDiv		1.5480
NSS			2.8234
IG			2.9752

File: gt\SH95.jpg
Metric		Ours	
Similarity	0.6913
CC			0.8134
AUC_Borji	0.6921
AUC_Judd	0.6922
KLDiv		0.9834
NSS			3.6651
IG			3.3317

File: gt\SH96.jpg
Metric		Ours	
Similarity	0.7167
CC			0.8408
AUC_Borji	0.8113
AUC_Judd	0.8115
KLDiv		3.1940
NSS			2.7621
IG			3.0531

File: gt\SH97.jpg
Metric		Ours	
Similarity	0.7962
CC			0.8798
AUC_Borji	0.8440	
AUC_Judd	0.8439
KLDiv		0.4578
NSS			2.4748
IG			2.5349

File: gt\SH98.jpg
Metric		Ours	
Similarity	0.7717
CC			0.7549
AUC_Borji	0.7134
AUC_Judd	0.7134
KLDiv		0.2548
NSS			2.4811
IG			2.1721

Although the model does not get as good results in this subset as it does in other cases, the metrics are quite good and are definitely better than the ones you shared with us.

Regards,

**Comment by PengWenChen** [comment]
Hello,

I've seen the evaluation code from the link you shared, and it's correct with these functions when calculating on 2d images.
In salient!360 2017 dataset, the evaluation codes they gave were the same as these matlab codes.
But in [salient!360 2018 benchmark](https://salient360.ls2n.fr/), they did some changes that they will multiply different weights to the equirectangular images since the pole distortions.
So, it might because you choose to seen equal to each pixel so the scores will be good since there are many black pixels in north and south poles.

p.s. The website of salient!360 2018 benchmark is under maintenance, so I pushed the measure code [here](https://github.com/PengWenChen/Saliency360_Eval.git).


Regards,

**Comment by PengWenChen** [comment]
Oh
I just saw the gt file name you gave.
Was the model trained with only headmovement saliency map?
Because I was focusing on head+eye saliency.
If so, then the difference in grades is reasonable.

**Comment by DaniMS-ZGZ** [comment]
Hi:

The 2018 benchmark modifications look reasonable. It is an interesting avenue to take those 360-aware metrics into account. Thanks for sharing this. 

This particular model we shared was trained with head movements, although the same architecture can be leveraged to train a model changing the dataset to a Head+Gaze one. 

I hope everything is clear now. 

Regards,
