### ISSUE TITLE
Fixation map groundtruth

### ISSUE THREAD

**Issue by PengWenChen** [DaniMS-ZGZ/Panoramic-CNN-360-Saliency#3]
Hi, it's me again.

I tried the evaluation code that you shared, and changed the ground truth to the head movement only heatmap. (Like bellow)
(read them as grayscal)
![SH91](https://user-images.githubusercontent.com/37527080/90713657-6562ab80-e2d8-11ea-87e6-7d6112401100.jpg)

The similarity and cc score are the same as you mentioned last time.
But the scores calculated with binary fixation maps are still different from the scores you gave, especially the NSS score.
I parsed the binary groundtruth by the code released in salient!360 2017 with 'SP*.txt' files. ([code](https://github.com/PengWenChen/Saliency360_Eval/blob/master/CompareHeadMaps.m))
I doubted that we did the same in this parsing step.
Could you also share the parsing code of binary fixation map?
Many thanks.

The scores are as follows.
![image](https://user-images.githubusercontent.com/37527080/90713473-fbe29d00-e2d7-11ea-9d79-14b67031f584.png)

By the way, it's also strange that the KLD score seems to be better than that you mentioned.

**Comment by DaniMS-ZGZ** [comment]
Hi.

We were not aware of that sparsing tool, neither those 'SP*.txt' files you mention, so we manually transformed the saliency maps into binary maps by thresholding the saliency maps, assuming zones with a higher saliency value came from fixations.

Regards,

**Comment by PengWenChen** [comment]
I see. 
What's the value of the threshold you set? 
Did you set the threshold with gray scale? For example, the pixel value is range from 0~255, and the threshold is maybe like 100.

**Comment by DaniMS-ZGZ** [comment]
Yes, it was set as a grayscale value. Values with saliency over 200 (this is, between 201 and 255) were assumed to come from fixations.

**Comment by PengWenChen** [comment]
Ok. Thanks for the response.
